### ISSUE TITLE
Awesome Idea

### ISSUE THREAD

**Issue by KoljaL** [basuke/vite-plugin-sveltekit-php-backend#1]
This is not an issue.

Just a praise for the idea and the implementation. 

How stable is the this way?

And does SSR work like with node?

Best regard Kolja

P.S.
I haven't tried yet, but I will as soon as I'm at home 😃

**Comment by basuke** [comment]
Thanks! Still is early stage of development, but stability is good. Unfortunately I'm getting very busy mode after May 12, so that I cannot make time to improve this project right now.
